package main;

// -- IMPORTS

import "fmt";

// -- FUNCTIONS

func main(
    )
{
    fmt.Println( "Tables :" );
    fmt.Println( "    SIMPLE," );
    fmt.Println( "        Columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            Bool," );
    fmt.Println( "            Int8," );
    fmt.Println( "            Uint8," );
    fmt.Println( "            Int16," );
    fmt.Println( "            Uint16," );
    fmt.Println( "            Int32," );
    fmt.Println( "            Uint32," );
    fmt.Println( "            Int64," );
    fmt.Println( "            Uint64," );
    fmt.Println( "            Float32," );
    fmt.Println( "            Float64," );
    fmt.Println( "            String," );
    fmt.Println( "            Date," );
    fmt.Println( "            DateTime," );
    fmt.Println( "            Blob" );
    fmt.Println( "        Key columns :" );
    fmt.Println( "            Uuid" );
    fmt.Println( "        Not key columns :" );
    fmt.Println( "            Bool," );
    fmt.Println( "            Int8," );
    fmt.Println( "            Uint8," );
    fmt.Println( "            Int16," );
    fmt.Println( "            Uint16," );
    fmt.Println( "            Int32," );
    fmt.Println( "            Uint32," );
    fmt.Println( "            Int64," );
    fmt.Println( "            Uint64," );
    fmt.Println( "            Float32," );
    fmt.Println( "            Float64," );
    fmt.Println( "            String," );
    fmt.Println( "            Date," );
    fmt.Println( "            DateTime," );
    fmt.Println( "            Blob" );
    fmt.Println( "        Stored columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            Bool," );
    fmt.Println( "            Int8," );
    fmt.Println( "            Uint8," );
    fmt.Println( "            Int16," );
    fmt.Println( "            Uint16," );
    fmt.Println( "            Int32," );
    fmt.Println( "            Uint32," );
    fmt.Println( "            Int64," );
    fmt.Println( "            Uint64," );
    fmt.Println( "            Float32," );
    fmt.Println( "            Float64," );
    fmt.Println( "            String," );
    fmt.Println( "            Date," );
    fmt.Println( "            DateTime," );
    fmt.Println( "            Blob" );
    fmt.Println( "        Not stored columns :" );
    fmt.Println( "    COMPOUND," );
    fmt.Println( "        Columns :" );
    fmt.Println( "            Id," );
    fmt.Println( "            Location," );
    fmt.Println( "            Name," );
    fmt.Println( "            NameSet," );
    fmt.Println( "            PhoneList," );
    fmt.Println( "            EmailSet," );
    fmt.Println( "            CompanyMap," );
    fmt.Println( "            SimpleDate," );
    fmt.Println( "            SimpleDateMap," );
    fmt.Println( "            SimpleDateSet," );
    fmt.Println( "            SimpleDateList," );
    fmt.Println( "            NameSetMap," );
    fmt.Println( "            SimplePointerArray" );
    fmt.Println( "        Key columns :" );
    fmt.Println( "            Id" );
    fmt.Println( "        Not key columns :" );
    fmt.Println( "            Location," );
    fmt.Println( "            Name," );
    fmt.Println( "            NameSet," );
    fmt.Println( "            PhoneList," );
    fmt.Println( "            EmailSet," );
    fmt.Println( "            CompanyMap," );
    fmt.Println( "            SimpleDate," );
    fmt.Println( "            SimpleDateMap," );
    fmt.Println( "            SimpleDateSet," );
    fmt.Println( "            SimpleDateList," );
    fmt.Println( "            NameSetMap," );
    fmt.Println( "            SimplePointerArray" );
    fmt.Println( "        Stored columns :" );
    fmt.Println( "            Id," );
    fmt.Println( "            Location," );
    fmt.Println( "            Name," );
    fmt.Println( "            NameSet," );
    fmt.Println( "            PhoneList," );
    fmt.Println( "            EmailSet," );
    fmt.Println( "            CompanyMap," );
    fmt.Println( "            SimpleDate," );
    fmt.Println( "            SimpleDateMap," );
    fmt.Println( "            SimpleDateSet," );
    fmt.Println( "            SimpleDateList," );
    fmt.Println( "            NameSetMap" );
    fmt.Println( "        Not stored columns :" );
    fmt.Println( "            SimplePointerArray" );
    fmt.Println( "    VALUE," );
    fmt.Println( "        Columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            Name," );
    fmt.Println( "            Integer," );
    fmt.Println( "            Text" );
    fmt.Println( "        Key columns :" );
    fmt.Println( "            Uuid" );
    fmt.Println( "        Not key columns :" );
    fmt.Println( "            Name," );
    fmt.Println( "            Integer," );
    fmt.Println( "            Text" );
    fmt.Println( "        Stored columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            Name," );
    fmt.Println( "            Integer," );
    fmt.Println( "            Text" );
    fmt.Println( "        Not stored columns :" );
    fmt.Println( "    DATA" );
    fmt.Println( "        Columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            ValueUuid" );
    fmt.Println( "        Key columns :" );
    fmt.Println( "            Uuid" );
    fmt.Println( "        Not key columns :" );
    fmt.Println( "            ValueUuid" );
    fmt.Println( "        Stored columns :" );
    fmt.Println( "            Uuid," );
    fmt.Println( "            ValueUuid" );
    fmt.Println( "        Not stored columns :" );
}
