TEST | count 10

    SIMPLE

        Uuid : UUID | key, unique
        Bool : BOOL | partitioned
        Int8 : INT8 | clustered
        Uint8 : UINT8 | indexed
        Int16 : INT16
        Uint16 : UINT16
        Int32 : INT32
        Uint32 : UINT32
        Int64 : INT64
        Uint64 : UINT64
        Float32 : FLOAT32
        Float64 : FLOAT64
        String : STRING
        Date : DATE | unique
        DateTime : DATETIME
        Blob : BLOB

    COMPOUND

        Id : INT32 | key, unique, incremented
        Location : Country : STRING | uppercase
        Name : TUPLE[ FirstName : STRING, LastName : STRING ] | unique
        NameSet : SET[ TUPLE[ FirstName : STRING, LastName : STRING ] ] | count 2
        PhoneList : LIST[ Phone : STRING ] | count 2
        EmailSet : SET[ Email : STRING ] | count 2
        CompanyMap : MAP[ Phone : STRING, Company : STRING ] | count 2
        SimpleDate : SIMPLE.Date
        SimpleDateMap : MAP[ COMPOUND.Name, SIMPLE.Date ] | count 2
        SimpleDateSet : SET[ SIMPLE.Date ] | count 2
        SimpleDateList : LIST[ SIMPLE.Date ] | count 1 3
        NameSetMap : MAP[ SIMPLE.Date, COMPOUND.NameSet ] | count 2
        SimplePointerArray : ARRAY[ POINTER[ SIMPLE ] ] | !stored

    VALUE | stored

        Id : INT64 | key
        Uuid : UUID | indexed
        Name : STRING
        Integer : INT32
        Text : STRING

    DATA

        Uuid : UUID | key
        ValueId : VALUE.Id
        ValueUuid : VALUE.Uuid
