TEST | count 10

    SIMPLE

        Uuid : UUID | key, unique
        Bool : BOOL | partitioned
        Int8 : INT8 | clustered
        Uint8 : UINT8 | indexed
        Int16 : INT16
        Uint16 : UINT16
        Int32 : INT32
        Uint32 : UINT32
        Int64 : INT64
        Uint64 : UINT64
        Float32 : FLOAT32
        Float64 : FLOAT64
        String : STRING
        Name : STRING
        Date : DATE | unique
        DateTime : DATETIME
        Blob : BLOB
        Option : STRING = "first_{{String}}|second_{{Name}}|third_{{Date}}|fourth_{{DateTime}}"

    COMPOUND

        Id : INT32 | key, unique, incremented
        Location : STRING | uppercase
        Name : TUPLE[ FirstName : STRING, LastName : STRING ] | unique
        NameSet : SET[ TUPLE[ FirstName : STRING, LastName : STRING ] ] | count 2
        PhoneList : LIST[ Phone : STRING ] | count 2
        EmailSet : SET[ Email : STRING ] | count 2
        CompanyMap : MAP[ Phone : STRING, Company : STRING ] | count 2
        SimpleDate : SIMPLE.Date
        SimpleDateMap : MAP[ COMPOUND.Name, SIMPLE.Date ] | count 2
        SimpleDateSet : SET[ SIMPLE.Date ] | count 2
        SimpleDateList : LIST[ SIMPLE.Date ] | count 1 3
        NameSetMap : MAP[ SIMPLE.Date, COMPOUND.NameSet ] | count 2
        Text : STRING
        SimplePointerArray : ARRAY[ POINTER[ SIMPLE ] ] | !stored

    VALUE | stored

        Id : INT64 | key
        Uuid : UUID | indexed
        Name : STRING
        Integer : INT32
        Text : STRING

    VALUE_DATA

        Uuid : UUID | key
        ValueId : VALUE.Id
        ValueUuid : VALUE.Uuid
        InternalId : INTERNAL_DATA.Id | !stored
        InternalUuid : INTERNAL_DATA.Uuid | !stored
        InternalValueId : INTERNAL_DATA.Id | !stored
        InternalValueUuid : INTERNAL_DATA.Uuid | !stored

    INTERNAL_DATA | !stored, has_button, button_size 10

        Id : INT64 | key, stored
        Uuid : UUID | key
        ValueId : VALUE.Id | stored
        ValueUuid : VALUE.Uuid | stored
        FirstName : STRING | !has_button
        LastName : STRING | !has_button
        IsAwesome : BOOL | has_button, button_size 10
